version: '3.8'

services:
  chat1:
    container_name: chat_cloud
    image: chat-test
    ports:
      - 3005:3005
    networks:
      - chat_network
  mongo:
    container_name: mongo4.2
    image: mongo:4.2
    restart: always
    ports:
      - 27017:27017
    volumes:
      - ./mongo/db:/data/db
      - ./mongo/configdb:/data/configdb
    networks:
      - chat_network
networks:
  chat_network:
    name: chat_network

